apiVersion: v2
# upstream version
appVersion: APP_VERSION_PLACEHOLDER
# giantswarm app version
version: CHART_VERSION_PLACEHOLDER
name: multus-cni
description: A CNI meta-plugin for multi-homed pods in Kubernetes
home: https://github.com/giantswarm/multus-cni
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  io.giantswarm.application.audience: "giantswarm"
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: "rocket"
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
sources:
  - https://github.com/k8snetworkplumbingwg/multus-cni
