apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- tmp/input/multus-daemonset-thick.yml

patches:
- path: patches/patch-daemonset.yaml

transformers:
  - patches/transformer-custom-labels.yaml
