apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: multus
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}'
    io.giantswarm.application.team: '{{ index .Chart.Annotations "io.giantswarm.application.team" }}'
    name: multus
    tier: node
  name: '{{ .Release.Name }}'
  namespace: '{{ .Release.Namespace }}'
spec:
  selector:
    matchLabels:
      name: multus
  template:
    metadata:
      labels:
        app: multus
        name: multus
        tier: node
    spec:
      containers:
        - command:
            - /usr/src/multus-cni/bin/multus-daemon
          env:
            - name: MULTUS_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: '{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}'
          name: kube-multus
          resources:
            limits:
              cpu: '{{ .Values.resources.limits.cpu }}'
              memory: '{{ .Values.resources.limits.memory }}'
            requests:
              cpu: '{{ .Values.resources.requests.cpu }}'
              memory: '{{ .Values.resources.requests.memory }}'
          securityContext:
            privileged: true
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /host/etc/cni/net.d
              name: cni
            - mountPath: /opt/cni/bin
              name: cnibin
            - mountPath: /host/run
              name: host-run
            - mountPath: /var/lib/cni/multus
              name: host-var-lib-cni-multus
            - mountPath: /var/lib/kubelet
              mountPropagation: HostToContainer
              name: host-var-lib-kubelet
            - mountPath: /run/k8s.cni.cncf.io
              name: host-run-k8s-cni-cncf-io
            - mountPath: /run/netns
              mountPropagation: HostToContainer
              name: host-run-netns
            - mountPath: /etc/cni/net.d/multus.d
              name: multus-daemon-config
              readOnly: true
            - mountPath: /hostroot
              mountPropagation: HostToContainer
              name: hostroot
            - mountPath: /etc/cni/multus/net.d
              name: multus-conf-dir
      hostNetwork: true
      hostPID: true
      initContainers:
        - command:
            - /usr/src/multus-cni/bin/install_multus
            - -d
            - /host/opt/cni/bin
            - -t
            - thick
          image: '{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}'
          name: install-multus-binary
          resources:
            requests:
              cpu: '{{ .Values.initContainer.resources.requests.cpu }}'
              memory: '{{ .Values.initContainer.resources.requests.memory }}'
          securityContext:
            privileged: true
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              mountPropagation: Bidirectional
              name: cnibin
      serviceAccountName: multus
      terminationGracePeriodSeconds: 10
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - hostPath:
            path: /etc/cni/net.d
          name: cni
        - hostPath:
            path: /opt/cni/bin
          name: cnibin
        - hostPath:
            path: /
          name: hostroot
        - configMap:
            items:
              - key: daemon-config.json
                path: daemon-config.json
            name: multus-daemon-config
          name: multus-daemon-config
        - hostPath:
            path: /run
          name: host-run
        - hostPath:
            path: /var/lib/cni/multus
          name: host-var-lib-cni-multus
        - hostPath:
            path: /var/lib/kubelet
          name: host-var-lib-kubelet
        - hostPath:
            path: /run/k8s.cni.cncf.io
          name: host-run-k8s-cni-cncf-io
        - hostPath:
            path: /run/netns/
          name: host-run-netns
        - hostPath:
            path: /etc/cni/multus/net.d
          name: multus-conf-dir
  updateStrategy:
    type: RollingUpdate
